DROP DATABASE IF EXISTS RPP2209;
CREATE DATABASE RPP2209;

USE RPP2209;

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
  id int NOT NULL AUTO_INCREMENT,
  studentName TEXT,
  git TEXT,
  gitUrl TEXT,
  PRIMARY KEY(id)
);
