DROP DATABASE IF EXISTS RPP2209;
CREATE DATABASE RPP2290;

USE RPP2209;

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
  id int NOT NULL AUTO_INCREMENT,
  name TEXT,
  git TEXT,
  link TEXT,
  PRIMARY KEY(id)
);